config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'links#index'
  resources :links do
    member do
      put 'like' => 'links#like'
      put 'dislike' => 'links#dislike'
    end
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
end

app/models/link.rb
class Link < ApplicationRecord
  has_many :comments
  belongs_to :user
  acts_as_votable
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :links
  has_many :comments
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    # @comment = Comment.new
    @link = Link.find(params[:link_id])
    @comment  = @link.comments.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @link = Link.find(params[:link_id])
    @comment = @link.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @link, notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body, :link_id, :user_id)
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!, except: %i[ index show ]
  before_action :set_link, only: %i[ show edit update destroy like dislike]

  # GET /links or /links.json
  def index
    @links = Link.all
  end

  # GET /links/1 or /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = current_user.links.build
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links or /links.json
  def create
    @link = current_user.links.build(link_params)
    # @link.user_id = current_user

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: "Link was successfully created." }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1 or /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: "Link was successfully updated." }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1 or /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: "Link was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def like
    if params[:format] == 'like'
      @link.liked_by current_user
    elsif params[:format] == 'unlike'
      @link.unliked_by current_user
    end
    redirect_back fallback_location: root_path
  end

  def dislike
    if params[:format] == 'dislike'
      @link.disliked_by current_user
    elsif params[:format] == 'undislike'
      @link.undisliked_by current_user
    end
    redirect_back fallback_location: root_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_link
    @link = Link.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def link_params
    params.require(:link).permit(:title, :url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [@link, @link.comments.build], local: true) do |form| %>
  <p>
    <br>
    <%= form.text_area :body, size: "40x5" %>
  </p>
  <p>
    <%= form.submit "Add Comment" %>
  </p>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
  <tr>
    <th>Body</th>
    <th>Link</th>
    <th>User</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @comments.each do |comment| %>
    <tr>
      <td><%= comment.body %></td>
      <td><%= comment.link_id %></td>
      <td><%= comment.user.email %></td>
<!--      <td><%#= link_to 'Show', comment %></td>-->
<!--      <td><%#= link_to 'Edit', edit_comment_path(comment) %></td>-->
<!--      <td><%#= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', link_comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Link:</strong>
  <%= @comment.link_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShareLink</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" integrity="sha512-8bHTC73gkZ7rZ7vpqUQThUDhqcNFyYi2xgDgPDHc+GXVGHXq+xPjynxIopALmOPqzo9JZj0k6OqqewdGO3EsrQ==" crossorigin="anonymous"/>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<% if user_signed_in? %>
  <ul>
    <li><%= link_to 'Edit Account', edit_user_registration_path %></li>
    <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
  </ul>
<% else %>
  <ul>
    <li><%= link_to 'Sign up', new_user_registration_path %></li>
    <li><%= link_to 'Sign in', new_user_session_path %></li>
  </ul>
<% end %>
<%= yield %>
<script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js" integrity="sha512-dqw6X88iGgZlTsONxZK9ePmJEFrmHwpuMrsUChjAw1mRUhUITE5QU9pkcSox+ynfLhL15Sv2al5A0LVyDCmtUw==" crossorigin="anonymous"></script>
</body>
</html>

app/views/links/_form.html.erb
<%= form_with(model: link, local: true) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
        <% link.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Links</h1>

<table>
  <thead>
  <tr>
    <th>Title</th>
    <th>Url</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @links.each do |link| %>
    <tr>
      <td><%= link.title %></td>
      <td><%= link.url %></td>
      <td><%= link_to 'Show', link %></td>
      <td><%= link_to 'Edit', edit_link_path(link) %></td>
      <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Link', new_link_path %>

<h1>Links</h1>
<% @links.each do |link| %>
  <div>
    <h2>
      <%= link_to link.title, link %><br>
      <small> Submitted <%= time_ago_in_words(link.created_at) %> by <%= link.user.email %></small>
    </h2>

    <div>
      <a href="<%= link.url %>">Go to Link</a>
      <% if user_signed_in? %>
        <% if current_user.liked? link %>
          <%= link_to 'unlike', like_link_path(link, 'unlike'), method: :put, remote: :true %>
        <% else %>
          <%= link_to 'like', like_link_path(link, 'like'), method: :put, remote: :true %>
        <% end %>
        <%= link.get_upvotes.size %>
        <% if current_user.disliked? link %>
          <%= link_to 'undislike', dislike_link_path(link, 'undislike'), method: :put, remote: :true %>
        <% else %>
          <%= link_to 'dislike', dislike_link_path(link, 'dislike'), method: :put, remote: :true %>
        <% end %>
        <%= link.get_downvotes.size %>
      <% end %>
    </div>
  </div>
<% end %>
<br>

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', links_path %>


<%# @link.each do |link| %>
  <%# if link.user_id == current_user %>
    <%#= link_to('Edit', edit_link_path(link)) %>
    <%#= link_to('Destroy', links_path(link), method: :delete, data: { confirm: 'Are you sure?' }) %>
  <%# end %>
<%# end %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @link.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @link.url %>
</p>

<% @link.comments.each do |comment| %>
  <p>
    <%= comment.user.email %>
    <small> Commented: </small>
    <%= comment.body %>
  </p>
<% end %>

<%= render 'comments/form' %>


<% if @link.user == current_user %>
  <%= link_to 'Edit', edit_link_path(@link) %> |
  <%= link_to 'Delete', @link, method: :delete %> |
<% end %>

<%= link_to 'Back', links_path %>